// example/next/02.preindexed/src/app/StaticSeek.tsx
import { useEffect, useRef, useState } from "react";
import type { JSX } from "react";
import { StaticSeekError, createIndexFromObject, search } from "staticseek";
import type { SearchResult, StaticSeekIndex } from "staticseek";

type StaticSeekProps = {
    query: string;
    indexUrl: string;
    suspense: JSX.Element;
    children: (result: SearchResult[]) => JSX.Element;
};

export default function StaticSeek({ query, indexUrl, suspense, children }: StaticSeekProps) {
    const index = useRef<StaticSeekIndex | null>(null);
    const [loading, setLoading] = useState<boolean>(true);
    const [result, setResult] = useState<SearchResult[]>([]);

    const search_async = async () => {
        if (index.current) {
            const start = performance.now();
            const result = await search(index.current, query);
            if (result instanceof StaticSeekError) {
                console.error(`fail to search: ${result.message}`);
                return;
            }
            console.log(`search took ${performance.now() - start} ms`);
            setResult(result);
        }
    };

    // biome-ignore lint: ignore dependencies
    useEffect(() => {
        const fetchIndex = async () => {
            const start = performance.now();
            const response = await fetch(indexUrl);
            if (!response.ok) {
                console.error(`fail to fetch index: ${response.statusText}`);
                return;
            }
            const response_json = await response.json();
            const newIndex = createIndexFromObject(response_json);
            if (newIndex instanceof StaticSeekError) {
                console.error(`fail to create index: ${newIndex.message}`);
                return;
            }
            console.log(`loading index took ${performance.now() - start} ms`);
            index.current = newIndex;
            setLoading(false);
            search_async();
        };

        if (index.current === null) {
            fetchIndex();
        }

        return () => {};
    }, []);

    // biome-ignore lint: include dependencies for search_async
    useEffect(() => {
        search_async();
        return () => {};
    }, [index, query]);

    return loading ? suspense : children(result);
}

// example/nuxt/02.preindexed/component/StaticSeek.vue
<script setup lang="tsx">
import type { SearchResult, StaticSeekIndex } from "staticseek";
import { StaticSeekError, createIndexFromObject, search } from "staticseek";

interface Props {
    query: string,
    url: string,
}
const { query, url } = defineProps<Props>();

const index = ref<StaticSeekIndex>();
const loading = ref(true);
const results = ref<SearchResult[]>([]);

async function init() {
    const start = performance.now();
    const { data } = await useFetch<StaticSeekIndex>(url);
    if (!data.value) {
        throw new Error("Failed to fetch search index.");
    }
    const newIndex = createIndexFromObject(data.value);

    if (newIndex instanceof StaticSeekError) {
        throw newIndex;
    }
    console.log("Loading index took", performance.now() - start, " ms");

    index.value = newIndex;
    loading.value = false;
}

watch(() => query, async (q) => {
    if (!index.value) {
        results.value = [];
        return ;
    }
    const start = performance.now();
    const searchResults = await search(index.value, q);
    if (searchResults instanceof StaticSeekError) {
        console.error(searchResults);
        results.value = [];
        return;
    }
    console.log("Searching took", performance.now() - start, " ms");

    results.value = searchResults;
});

init();
</script>

<template>
    <template v-if="loading">
        <slot name="suspence"></slot>
    </template>
    <template v-else>
        <slot name="default" :results="results"></slot>
    </template>
</template>
